### ISSUE TITLE
Active #[cfg(test)] by default

### ISSUE THREAD

**Issue by xdatcloud** [jackos/rustlings-fix#1]
It would be better to active `#[cfg(test)]` by default with config below to each crates:

```json
        {
            "root_module": "exercises/advanced_errors/advanced_errs1.rs",
            "edition": "2021",
            "deps": [],
            "cfg": ["test"]
        },
```

Thanks for creating this small & sweet tool to improve experience on rustlings with RA ❤️.

**Comment by jackos** [comment]
Thanks for the suggestion @xdatcloud, what effect will that have?

**Comment by xdatcloud** [comment]
> Thanks for the suggestion @xdatcloud, what effect will that have?

Some exercises like `exercises/structs/structs2.rs`, We need to address todos in `mod tests`, and `mod` is attributed with `#[cfg(test)]`.

With default `rust-project.json` generated by rustlings-fix, rust analyzer intellisense/autocomplete (for vscode) not working due to `#[cfg(test)]` is [inactive](https://rust-analyzer.github.io/manual.html#inactive-code).

To active `#[cfg(test)]`, we should add `"cfg": ["test"]` to each crates in `rust-project.json` just like first comment shows, and thus intellisense/autocomplete in `mod tests` will be enabled.

**Comment by jackos** [comment]
Cool thanks for the explanation @xdatcloud , I made the change
